# Compiler
CC = mpicc

# Compiler flags
CFLAGS = -std=c99 -O2

# Target executable name
TARGET = heat_equation_mpi

# Source file
SRC = heat_equation_mpi.c

# Math library
LIBS = -lm

# Default number of processes, which can be overridden from the command line
NP ?= 4

# Default rule: build the target
all: $(TARGET)

# Rule to build the executable
$(TARGET): $(SRC)
	$(CC) $(CFLAGS) -o $(TARGET) $(SRC) $(LIBS)

# Rule to run the program
run: $(TARGET)
	mpirun -np $(NP) ./$(TARGET)

# Clean and run the program
cleanrun: clean run

# Rule to clean the build files and all files generated by the build result_*
clean:
	rm -f $(TARGET)
	rm -f *.dat

# Rule to recompile the program
rebuild: clean all
